// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASIrwnNX4k8E4v2pyCg42UY6xF7VyoaiE',
    appId: '1:701252937477:web:517d146ce2519b890f396c',
    messagingSenderId: '701252937477',
    projectId: 'sogongtest-c066f',
    authDomain: 'sogongtest-c066f.firebaseapp.com',
    storageBucket: 'sogongtest-c066f.firebasestorage.app',
    measurementId: 'G-R14EQRCTPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMAA8FQWDKJUPQOtS3-2SQuJGEZ4Emt-0',
    appId: '1:701252937477:android:5ec4cd697b51af9c0f396c',
    messagingSenderId: '701252937477',
    projectId: 'sogongtest-c066f',
    storageBucket: 'sogongtest-c066f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAedIXloI8WMJCHCGhPo_Ksm1FYsLcxLv0',
    appId: '1:701252937477:ios:da881d5971d475130f396c',
    messagingSenderId: '701252937477',
    projectId: 'sogongtest-c066f',
    storageBucket: 'sogongtest-c066f.firebasestorage.app',
    iosBundleId: 'com.example.sogong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAedIXloI8WMJCHCGhPo_Ksm1FYsLcxLv0',
    appId: '1:701252937477:ios:da881d5971d475130f396c',
    messagingSenderId: '701252937477',
    projectId: 'sogongtest-c066f',
    storageBucket: 'sogongtest-c066f.firebasestorage.app',
    iosBundleId: 'com.example.sogong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASIrwnNX4k8E4v2pyCg42UY6xF7VyoaiE',
    appId: '1:701252937477:web:86e7fad75d4241130f396c',
    messagingSenderId: '701252937477',
    projectId: 'sogongtest-c066f',
    authDomain: 'sogongtest-c066f.firebaseapp.com',
    storageBucket: 'sogongtest-c066f.firebasestorage.app',
    measurementId: 'G-TYZ8V48RM3',
  );
}
